//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class BondIterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BondIterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BondIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BondIterator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RDKFuncsPINVOKE.delete_BondIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public BondIterator() : this(RDKFuncsPINVOKE.new_BondIterator__SWIG_0(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public BondIterator(ROMol mol) : this(RDKFuncsPINVOKE.new_BondIterator__SWIG_1(ROMol.getCPtr(mol)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public BondIterator(ROMol mol, SWIGTYPE_p_boost__adjacency_listT_boost__vecS_boost__vecS_boost__undirectedS_RDKit__Atom_p_RDKit__Bond_p_t__edge_iterator pos) : this(RDKFuncsPINVOKE.new_BondIterator__SWIG_2(ROMol.getCPtr(mol), SWIGTYPE_p_boost__adjacency_listT_boost__vecS_boost__vecS_boost__undirectedS_RDKit__Atom_p_RDKit__Bond_p_t__edge_iterator.getCPtr(pos)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public BondIterator(BondIterator other) : this(RDKFuncsPINVOKE.new_BondIterator__SWIG_3(BondIterator.getCPtr(other)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool eq(BondIterator other) {
    bool ret = RDKFuncsPINVOKE.BondIterator_eq(swigCPtr, BondIterator.getCPtr(other));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool ne(BondIterator other) {
    bool ret = RDKFuncsPINVOKE.BondIterator_ne(swigCPtr, BondIterator.getCPtr(other));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Bond getBond() {
    global::System.IntPtr cPtr = RDKFuncsPINVOKE.BondIterator_getBond(swigCPtr);
    Bond ret = (cPtr == global::System.IntPtr.Zero) ? null : new Bond(cPtr, true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public BondIterator next() {
    BondIterator ret = new BondIterator(RDKFuncsPINVOKE.BondIterator_next__SWIG_0(swigCPtr), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public BondIterator next(int arg0) {
    BondIterator ret = new BondIterator(RDKFuncsPINVOKE.BondIterator_next__SWIG_1(swigCPtr, arg0), true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public BondIterator prev() {
    BondIterator ret = new BondIterator(RDKFuncsPINVOKE.BondIterator_prev__SWIG_0(swigCPtr), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public BondIterator prev(int arg0) {
    BondIterator ret = new BondIterator(RDKFuncsPINVOKE.BondIterator_prev__SWIG_1(swigCPtr, arg0), true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
