//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class DistanceConstraintContrib : ForceFieldContrib {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal DistanceConstraintContrib(global::System.IntPtr cPtr, bool cMemoryOwn) : base(RDKFuncsPINVOKE.DistanceConstraintContrib_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DistanceConstraintContrib obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DistanceConstraintContrib() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          RDKFuncsPINVOKE.delete_DistanceConstraintContrib(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DistanceConstraintContrib() : this(RDKFuncsPINVOKE.new_DistanceConstraintContrib__SWIG_0(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public DistanceConstraintContrib(ForceField owner, uint idx1, uint idx2, double minLen, double maxLen, double forceConst) : this(RDKFuncsPINVOKE.new_DistanceConstraintContrib__SWIG_1(ForceField.getCPtr(owner), idx1, idx2, minLen, maxLen, forceConst), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public DistanceConstraintContrib(ForceField owner, uint idx1, uint idx2, bool relative, double minLen, double maxLen, double forceConst) : this(RDKFuncsPINVOKE.new_DistanceConstraintContrib__SWIG_2(ForceField.getCPtr(owner), idx1, idx2, relative, minLen, maxLen, forceConst), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getEnergy(SWIGTYPE_p_double pos) {
    double ret = RDKFuncsPINVOKE.DistanceConstraintContrib_getEnergy(swigCPtr, SWIGTYPE_p_double.getCPtr(pos));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void getGrad(SWIGTYPE_p_double pos, SWIGTYPE_p_double grad) {
    RDKFuncsPINVOKE.DistanceConstraintContrib_getGrad(swigCPtr, SWIGTYPE_p_double.getCPtr(pos), SWIGTYPE_p_double.getCPtr(grad));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ForceFieldContrib copy() {
    global::System.IntPtr cPtr = RDKFuncsPINVOKE.DistanceConstraintContrib_copy(swigCPtr);
    DistanceConstraintContrib ret = (cPtr == global::System.IntPtr.Zero) ? null : new DistanceConstraintContrib(cPtr, true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
