//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class IntMatrix : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IntMatrix(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IntMatrix obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IntMatrix() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RDKFuncsPINVOKE.delete_IntMatrix(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public IntMatrix(uint nRows, uint nCols) : this(RDKFuncsPINVOKE.new_IntMatrix__SWIG_0(nRows, nCols), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntMatrix(uint nRows, uint nCols, int val) : this(RDKFuncsPINVOKE.new_IntMatrix__SWIG_1(nRows, nCols, val), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntMatrix(uint nRows, uint nCols, Shared_Int_Array data) : this(RDKFuncsPINVOKE.new_IntMatrix__SWIG_2(nRows, nCols, Shared_Int_Array.getCPtr(data)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public IntMatrix(IntMatrix other) : this(RDKFuncsPINVOKE.new_IntMatrix__SWIG_3(IntMatrix.getCPtr(other)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint numRows() {
    uint ret = RDKFuncsPINVOKE.IntMatrix_numRows(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numCols() {
    uint ret = RDKFuncsPINVOKE.IntMatrix_numCols(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getDataSize() {
    uint ret = RDKFuncsPINVOKE.IntMatrix_getDataSize(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int getVal(uint i, uint j) {
    int ret = RDKFuncsPINVOKE.IntMatrix_getVal(swigCPtr, i, j);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setVal(uint i, uint j, int val) {
    RDKFuncsPINVOKE.IntMatrix_setVal(swigCPtr, i, j, val);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getRow(uint i, SWIGTYPE_p_RDNumeric__VectorT_int_t row) {
    RDKFuncsPINVOKE.IntMatrix_getRow(swigCPtr, i, SWIGTYPE_p_RDNumeric__VectorT_int_t.getCPtr(row));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void getCol(uint i, SWIGTYPE_p_RDNumeric__VectorT_int_t col) {
    RDKFuncsPINVOKE.IntMatrix_getCol(swigCPtr, i, SWIGTYPE_p_RDNumeric__VectorT_int_t.getCPtr(col));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_int getData() {
    global::System.IntPtr cPtr = RDKFuncsPINVOKE.IntMatrix_getData__SWIG_0(swigCPtr);
    SWIGTYPE_p_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_int(cPtr, false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IntMatrix assign(IntMatrix other) {
    IntMatrix ret = new IntMatrix(RDKFuncsPINVOKE.IntMatrix_assign(swigCPtr, IntMatrix.getCPtr(other)), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual IntMatrix transpose(IntMatrix transpose) {
    IntMatrix ret = new IntMatrix(RDKFuncsPINVOKE.IntMatrix_transpose(swigCPtr, IntMatrix.getCPtr(transpose)), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
