//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class Long_Pair_Vect : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<Long_Pair>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Long_Pair_Vect(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Long_Pair_Vect obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Long_Pair_Vect() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RDKFuncsPINVOKE.delete_Long_Pair_Vect(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Long_Pair_Vect(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Long_Pair element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Long_Pair this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Long_Pair[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Long_Pair[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Long_Pair[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<Long_Pair> global::System.Collections.Generic.IEnumerable<Long_Pair>.GetEnumerator() {
    return new Long_Pair_VectEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new Long_Pair_VectEnumerator(this);
  }

  public Long_Pair_VectEnumerator GetEnumerator() {
    return new Long_Pair_VectEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class Long_Pair_VectEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Long_Pair>
  {
    private Long_Pair_Vect collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public Long_Pair_VectEnumerator(Long_Pair_Vect collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Long_Pair Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Long_Pair)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    RDKFuncsPINVOKE.Long_Pair_Vect_Clear(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(Long_Pair x) {
    RDKFuncsPINVOKE.Long_Pair_Vect_Add(swigCPtr, Long_Pair.getCPtr(x));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = RDKFuncsPINVOKE.Long_Pair_Vect_size(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = RDKFuncsPINVOKE.Long_Pair_Vect_capacity(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    RDKFuncsPINVOKE.Long_Pair_Vect_reserve(swigCPtr, n);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Long_Pair_Vect() : this(RDKFuncsPINVOKE.new_Long_Pair_Vect__SWIG_0(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Long_Pair_Vect(Long_Pair_Vect other) : this(RDKFuncsPINVOKE.new_Long_Pair_Vect__SWIG_1(Long_Pair_Vect.getCPtr(other)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Long_Pair_Vect(int capacity) : this(RDKFuncsPINVOKE.new_Long_Pair_Vect__SWIG_2(capacity), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  private Long_Pair getitemcopy(int index) {
    Long_Pair ret = new Long_Pair(RDKFuncsPINVOKE.Long_Pair_Vect_getitemcopy(swigCPtr, index), true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Long_Pair getitem(int index) {
    Long_Pair ret = new Long_Pair(RDKFuncsPINVOKE.Long_Pair_Vect_getitem(swigCPtr, index), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Long_Pair val) {
    RDKFuncsPINVOKE.Long_Pair_Vect_setitem(swigCPtr, index, Long_Pair.getCPtr(val));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Long_Pair_Vect values) {
    RDKFuncsPINVOKE.Long_Pair_Vect_AddRange(swigCPtr, Long_Pair_Vect.getCPtr(values));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public Long_Pair_Vect GetRange(int index, int count) {
    global::System.IntPtr cPtr = RDKFuncsPINVOKE.Long_Pair_Vect_GetRange(swigCPtr, index, count);
    Long_Pair_Vect ret = (cPtr == global::System.IntPtr.Zero) ? null : new Long_Pair_Vect(cPtr, true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Long_Pair x) {
    RDKFuncsPINVOKE.Long_Pair_Vect_Insert(swigCPtr, index, Long_Pair.getCPtr(x));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Long_Pair_Vect values) {
    RDKFuncsPINVOKE.Long_Pair_Vect_InsertRange(swigCPtr, index, Long_Pair_Vect.getCPtr(values));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    RDKFuncsPINVOKE.Long_Pair_Vect_RemoveAt(swigCPtr, index);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    RDKFuncsPINVOKE.Long_Pair_Vect_RemoveRange(swigCPtr, index, count);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Long_Pair_Vect Repeat(Long_Pair value, int count) {
    global::System.IntPtr cPtr = RDKFuncsPINVOKE.Long_Pair_Vect_Repeat(Long_Pair.getCPtr(value), count);
    Long_Pair_Vect ret = (cPtr == global::System.IntPtr.Zero) ? null : new Long_Pair_Vect(cPtr, true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    RDKFuncsPINVOKE.Long_Pair_Vect_Reverse__SWIG_0(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    RDKFuncsPINVOKE.Long_Pair_Vect_Reverse__SWIG_1(swigCPtr, index, count);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Long_Pair_Vect values) {
    RDKFuncsPINVOKE.Long_Pair_Vect_SetRange(swigCPtr, index, Long_Pair_Vect.getCPtr(values));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool equals(Long_Pair_Vect o) {
    bool ret = RDKFuncsPINVOKE.Long_Pair_Vect_equals(swigCPtr, Long_Pair_Vect.getCPtr(o));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
