//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class RGroupDecompositionParameters : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RGroupDecompositionParameters(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RGroupDecompositionParameters obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RGroupDecompositionParameters() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RDKFuncsPINVOKE.delete_RGroupDecompositionParameters(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint labels {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_labels_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_labels_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint matchingStrategy {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_matchingStrategy_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_matchingStrategy_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint scoreMethod {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_scoreMethod_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_scoreMethod_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint rgroupLabelling {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_rgroupLabelling_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_rgroupLabelling_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint alignment {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_alignment_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_alignment_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint chunkSize {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_chunkSize_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_chunkSize_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool onlyMatchAtRGroups {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_onlyMatchAtRGroups_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_onlyMatchAtRGroups_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool removeAllHydrogenRGroups {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_removeAllHydrogenRGroups_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_removeAllHydrogenRGroups_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool removeAllHydrogenRGroupsAndLabels {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_removeAllHydrogenRGroupsAndLabels_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_removeAllHydrogenRGroupsAndLabels_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool removeHydrogensPostMatch {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_removeHydrogensPostMatch_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_removeHydrogensPostMatch_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool allowNonTerminalRGroups {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_allowNonTerminalRGroups_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_allowNonTerminalRGroups_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public double timeout {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_timeout_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      double ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_timeout_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public uint autoGetLabels(RWMol arg0) {
    uint ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_autoGetLabels(swigCPtr, RWMol.getCPtr(arg0));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool prepareCore(RWMol arg0, RWMol alignCore) {
    bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_prepareCore(swigCPtr, RWMol.getCPtr(arg0), RWMol.getCPtr(alignCore));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int gaPopulationSize {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_gaPopulationSize_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_gaPopulationSize_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int gaMaximumOperations {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_gaMaximumOperations_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_gaMaximumOperations_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int gaNumberOperationsWithoutImprovement {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_gaNumberOperationsWithoutImprovement_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_gaNumberOperationsWithoutImprovement_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int gaRandomSeed {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_gaRandomSeed_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_gaRandomSeed_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int gaNumberRuns {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_gaNumberRuns_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_gaNumberRuns_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool gaParallelRuns {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_gaParallelRuns_set(swigCPtr, value);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = RDKFuncsPINVOKE.RGroupDecompositionParameters_gaParallelRuns_get(swigCPtr);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SubstructMatchParameters substructmatchParams {
    set {
      RDKFuncsPINVOKE.RGroupDecompositionParameters_substructmatchParams_set(swigCPtr, SubstructMatchParameters.getCPtr(value));
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = RDKFuncsPINVOKE.RGroupDecompositionParameters_substructmatchParams_get(swigCPtr);
      SubstructMatchParameters ret = (cPtr == global::System.IntPtr.Zero) ? null : new SubstructMatchParameters(cPtr, false);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public RGroupDecompositionParameters() : this(RDKFuncsPINVOKE.new_RGroupDecompositionParameters(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
