//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public enum RGroupMatching {
  Greedy = 0x01,
  GreedyChunks = 0x02,
  Exhaustive = 0x04,
  NoSymmetrization = 0x08,
  GA = 0x10
}

}
