//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class RingInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal RingInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RingInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RingInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          RDKFuncsPINVOKE.delete_RingInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public RingInfo() : this(RDKFuncsPINVOKE.new_RingInfo__SWIG_0(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public RingInfo(RingInfo other) : this(RDKFuncsPINVOKE.new_RingInfo__SWIG_1(RingInfo.getCPtr(other)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isInitialized() {
    bool ret = RDKFuncsPINVOKE.RingInfo_isInitialized(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void initialize() {
    RDKFuncsPINVOKE.RingInfo_initialize(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    RDKFuncsPINVOKE.RingInfo_reset(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint addRing(Int_Vect atomIndices, Int_Vect bondIndices) {
    uint ret = RDKFuncsPINVOKE.RingInfo_addRing(swigCPtr, Int_Vect.getCPtr(atomIndices), Int_Vect.getCPtr(bondIndices));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Int_Vect atomRingSizes(uint idx) {
    Int_Vect ret = new Int_Vect(RDKFuncsPINVOKE.RingInfo_atomRingSizes(swigCPtr, idx), true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isAtomInRingOfSize(uint idx, uint size) {
    bool ret = RDKFuncsPINVOKE.RingInfo_isAtomInRingOfSize(swigCPtr, idx, size);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numAtomRings(uint idx) {
    uint ret = RDKFuncsPINVOKE.RingInfo_numAtomRings(swigCPtr, idx);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint minAtomRingSize(uint idx) {
    uint ret = RDKFuncsPINVOKE.RingInfo_minAtomRingSize(swigCPtr, idx);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Int_Vect_Vect atomRings() {
    Int_Vect_Vect ret = new Int_Vect_Vect(RDKFuncsPINVOKE.RingInfo_atomRings(swigCPtr), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Int_Vect bondRingSizes(uint idx) {
    Int_Vect ret = new Int_Vect(RDKFuncsPINVOKE.RingInfo_bondRingSizes(swigCPtr, idx), true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isBondInRingOfSize(uint idx, uint size) {
    bool ret = RDKFuncsPINVOKE.RingInfo_isBondInRingOfSize(swigCPtr, idx, size);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numBondRings(uint idx) {
    uint ret = RDKFuncsPINVOKE.RingInfo_numBondRings(swigCPtr, idx);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint minBondRingSize(uint idx) {
    uint ret = RDKFuncsPINVOKE.RingInfo_minBondRingSize(swigCPtr, idx);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numRings() {
    uint ret = RDKFuncsPINVOKE.RingInfo_numRings(swigCPtr);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Int_Vect_Vect bondRings() {
    Int_Vect_Vect ret = new Int_Vect_Vect(RDKFuncsPINVOKE.RingInfo_bondRings(swigCPtr), false);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
