//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public enum SanitizeFlags {
  SANITIZE_NONE = 0x0,
  SANITIZE_CLEANUP = 0x1,
  SANITIZE_PROPERTIES = 0x2,
  SANITIZE_SYMMRINGS = 0x4,
  SANITIZE_KEKULIZE = 0x8,
  SANITIZE_FINDRADICALS = 0x10,
  SANITIZE_SETAROMATICITY = 0x20,
  SANITIZE_SETCONJUGATION = 0x40,
  SANITIZE_SETHYBRIDIZATION = 0x80,
  SANITIZE_CLEANUPCHIRALITY = 0x100,
  SANITIZE_ADJUSTHS = 0x200,
  SANITIZE_ALL = 0xFFFFFFF
}

}
