//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class ScaffoldNetwork : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ScaffoldNetwork(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ScaffoldNetwork obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ScaffoldNetwork() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          RDKFuncsPINVOKE.delete_ScaffoldNetwork(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Str_Vect nodes {
    set {
      RDKFuncsPINVOKE.ScaffoldNetwork_nodes_set(swigCPtr, Str_Vect.getCPtr(value));
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = RDKFuncsPINVOKE.ScaffoldNetwork_nodes_get(swigCPtr);
      Str_Vect ret = (cPtr == global::System.IntPtr.Zero) ? null : new Str_Vect(cPtr, false);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public UInt_Vect counts {
    set {
      RDKFuncsPINVOKE.ScaffoldNetwork_counts_set(swigCPtr, UInt_Vect.getCPtr(value));
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = RDKFuncsPINVOKE.ScaffoldNetwork_counts_get(swigCPtr);
      UInt_Vect ret = (cPtr == global::System.IntPtr.Zero) ? null : new UInt_Vect(cPtr, false);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public UInt_Vect molCounts {
    set {
      RDKFuncsPINVOKE.ScaffoldNetwork_molCounts_set(swigCPtr, UInt_Vect.getCPtr(value));
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = RDKFuncsPINVOKE.ScaffoldNetwork_molCounts_get(swigCPtr);
      UInt_Vect ret = (cPtr == global::System.IntPtr.Zero) ? null : new UInt_Vect(cPtr, false);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public NetworkEdge_Vect edges {
    set {
      RDKFuncsPINVOKE.ScaffoldNetwork_edges_set(swigCPtr, NetworkEdge_Vect.getCPtr(value));
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = RDKFuncsPINVOKE.ScaffoldNetwork_edges_get(swigCPtr);
      NetworkEdge_Vect ret = (cPtr == global::System.IntPtr.Zero) ? null : new NetworkEdge_Vect(cPtr, false);
      if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ScaffoldNetwork() : this(RDKFuncsPINVOKE.new_ScaffoldNetwork(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint nodeCount(uint nodeNumber) {
    uint ret = RDKFuncsPINVOKE.ScaffoldNetwork_nodeCount(swigCPtr, nodeNumber);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
