//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GraphMolWrap {

public class TorsionAngleContrib : ForceFieldContrib {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal TorsionAngleContrib(global::System.IntPtr cPtr, bool cMemoryOwn) : base(RDKFuncsPINVOKE.TorsionAngleContrib_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TorsionAngleContrib obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TorsionAngleContrib() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          RDKFuncsPINVOKE.delete_TorsionAngleContrib(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public TorsionAngleContrib() : this(RDKFuncsPINVOKE.new_TorsionAngleContrib__SWIG_0(), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public TorsionAngleContrib(ForceField owner, uint idx1, uint idx2, uint idx3, uint idx4, double bondOrder23, int atNum2, int atNum3, Atom.HybridizationType hyb2, Atom.HybridizationType hyb3, AtomicParams at2Params, AtomicParams at3Params, bool endAtomIsSP2) : this(RDKFuncsPINVOKE.new_TorsionAngleContrib__SWIG_1(ForceField.getCPtr(owner), idx1, idx2, idx3, idx4, bondOrder23, atNum2, atNum3, (int)hyb2, (int)hyb3, AtomicParams.getCPtr(at2Params), AtomicParams.getCPtr(at3Params), endAtomIsSP2), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public TorsionAngleContrib(ForceField owner, uint idx1, uint idx2, uint idx3, uint idx4, double bondOrder23, int atNum2, int atNum3, Atom.HybridizationType hyb2, Atom.HybridizationType hyb3, AtomicParams at2Params, AtomicParams at3Params) : this(RDKFuncsPINVOKE.new_TorsionAngleContrib__SWIG_2(ForceField.getCPtr(owner), idx1, idx2, idx3, idx4, bondOrder23, atNum2, atNum3, (int)hyb2, (int)hyb3, AtomicParams.getCPtr(at2Params), AtomicParams.getCPtr(at3Params)), true) {
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override double getEnergy(SWIGTYPE_p_double pos) {
    double ret = RDKFuncsPINVOKE.TorsionAngleContrib_getEnergy(swigCPtr, SWIGTYPE_p_double.getCPtr(pos));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void getGrad(SWIGTYPE_p_double pos, SWIGTYPE_p_double grad) {
    RDKFuncsPINVOKE.TorsionAngleContrib_getGrad(swigCPtr, SWIGTYPE_p_double.getCPtr(pos), SWIGTYPE_p_double.getCPtr(grad));
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public void scaleForceConstant(uint count) {
    RDKFuncsPINVOKE.TorsionAngleContrib_scaleForceConstant(swigCPtr, count);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
  }

  public override ForceFieldContrib copy() {
    global::System.IntPtr cPtr = RDKFuncsPINVOKE.TorsionAngleContrib_copy(swigCPtr);
    TorsionAngleContrib ret = (cPtr == global::System.IntPtr.Zero) ? null : new TorsionAngleContrib(cPtr, true);
    if (RDKFuncsPINVOKE.SWIGPendingException.Pending) throw RDKFuncsPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
